import http from "node:http";
import { spawn } from "node:child_process";
import { createReadStream } from "node:fs";
import { readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { Readable } from "node:stream";
import { fileURLToPath } from "node:url";
import path from "node:path";
import crypto from "node:crypto";
import { createRequire } from "node:module";
import { generateCompositionWithPiAgent, modifyCompositionWithPiAgent } from "./pi-agent.mjs";
import { createAudioStore } from "./audio-store.mjs";
import { STYLES, getStyle, detectStyle } from "./styles.mjs";
const require = createRequire(import.meta.url);
const ffmpegBinary = (() => { try { return require("ffmpeg-static"); } catch { return null; } })();

const root=path.dirname(path.dirname(fileURLToPath(import.meta.url))), stateFile=path.join(root,"data/editing-state.json"), compositionDir=path.join(root,"hyperframes"), compositionFile=path.join(compositionDir,"index.html"), outputDir=path.join(root,"output"), hyperframesScript=path.join(root,"node_modules/hyperframes/bin/hyperframes.mjs"), port=Number(process.env.AGENT_PORT||8787), jobs=new Map();
try{process.loadEnvFile(path.join(root,".env"))}catch(error){if(error?.code!=="ENOENT")throw error}
await mkdir(outputDir,{recursive:true});
const ffprobePlatform=process.platform==="win32"?"win32":process.platform,ffprobeArch=process.platform==="win32"?(process.arch==="ia32"?"ia32":"x64"):process.arch==="arm64"?"arm64":"x64",ffprobePath=path.join(root,"node_modules/ffprobe-static/bin",ffprobePlatform,ffprobeArch,process.platform==="win32"?"ffprobe.exe":"ffprobe"),audioStore=createAudioStore({root,ffprobePath});
let projectVersion=0;const SEGMENT_SECONDS=Number(process.env.SEGMENT_SECONDS||30);
const json=(res,value,status=200)=>{res.writeHead(status,{"content-type":"application/json; charset=utf-8"});res.end(JSON.stringify(value))};
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
const escapeAttr=value=>escapeHtml(String(value));
async function state(){return JSON.parse(await readFile(stateFile,"utf8"))}

async function applyAudioTrack(html,segStartFrame=0,segDurationFrames=Infinity){const clean=html.replace(/<!-- hypercut-audio:start -->[\s\S]*?<!-- hypercut-audio:end -->/g,"").replace(/<audio\b[\s\S]*?<\/audio>/gi,"");const{track,selectedAsset}=await audioStore.resolveTrack();if(!track||!selectedAsset)return clean;const fps=24,aStart=track.startFrame,aEnd=track.endFrame,sStart=segStartFrame,sEnd=segStartFrame+segDurationFrames,iStart=Math.max(aStart,sStart),iEnd=Math.min(aEnd,sEnd);if(iEnd<=iStart)return clean;const start=(iStart-sStart)/fps,duration=(iEnd-iStart)/fps,trim=(track.trimStartFrame+(iStart-aStart))/fps,volume=track.muted?0:track.volume,fadeIn=Math.min(duration,track.fadeInFrames/fps),fadeOut=Math.min(duration,track.fadeOutFrames/fps),points=[];if(fadeIn>0)points.push({t:0,v:0},{t:fadeIn,v:volume});else points.push({t:0,v:volume});if(fadeOut>0)points.push({t:Math.max(fadeIn,duration-fadeOut),v:volume},{t:duration,v:0});else points.push({t:duration,v:volume});const automation=escapeAttr(JSON.stringify({version:1,lanes:[{target:"volume",points}]})),loop=track.loop?" loop":"",element=`<!-- hypercut-audio:start --><audio id="audio_main" class="clip" src="assets/${escapeAttr(selectedAsset.fileName)}" data-start="${start}" data-duration="${duration}" data-media-start="${trim}" data-track-index="20" data-volume="${volume}" data-automation="${automation}"${loop}></audio><!-- hypercut-audio:end -->`;return clean.replace(/<\/body>/i,`${element}</body>`)}

function cnNum(s){if(s==="半")return 0.5;const m={"零":0,"一":1,"二":2,"两":2,"三":3,"四":4,"五":5,"六":6,"七":7,"八":8,"九":9};if(s.length===1)return m[s]??NaN;if(s==="十")return 10;if(/^[一二两三四五六七八九]十$/.test(s))return m[s[0]]*10;if(/^十[一二三四五六七八九]$/.test(s))return 10+m[s[1]];if(/^[一二两三四五六七八九]十[一二三四五六七八九]$/.test(s))return m[s[0]]*10+m[s[2]];return NaN}
function parseDuration(prompt,fallback=6){const p=String(prompt||""),val=s=>/^\d/.test(s)?Number(s):cnNum(s),minM=p.match(/(\d+(?:\.\d+)?|[一二两三四五六七八九十半]+)\s*(?:分钟|分|min)/i),secM=p.match(/(\d+(?:\.\d+)?|[一二两三四五六七八九十半]+)\s*(?:秒|sec|s\b)/i);let total=0;if(minM){const n=val(minM[1]);if(!Number.isNaN(n))total+=n*60}if(secM){const n=val(secM[1]);if(!Number.isNaN(n))total+=n}return total>0?Math.max(1,Math.round(total)):fallback}
function forceSegmentDuration(html,dur){const re=/(<[^>]*\bdata-composition-id="hypercut-main"[^>]*\bdata-duration=")[^"]*(")/;if(re.test(html))return html.replace(re,`$1${dur}$2`);const re2=/(<[^>]*\bdata-duration=")[^"]*("[^>]*\bdata-composition-id="hypercut-main")/;if(re2.test(html))return html.replace(re2,`$1${dur}$2`);return html}
function understandPrompt(prompt,style){const quoted=prompt.match(/[“"]([^”"]{2,30})[”"]/),explicit=prompt.match(/(?:标题|主题|文案)(?:是|为|改成|写成|：|:)?\s*([^，。,.]{2,30})/),duration=Math.max(2,Math.min(60,parseDuration(prompt,6)));const title=(quoted?.[1]||explicit?.[1]||prompt.replace(/请|帮我|生成|制作|一个|一段|视频|宣传片|科技感|酷炫/g,"").trim()||"智创未来").slice(0,18);return{title,subtitle:/产品/.test(prompt)?"PRODUCT FILM · GENERATED BY π AGENT":"AGENT-NATIVE VIDEO · HYPERFRAMES",palette:style.palette,duration}}

function generateComposition(spec){const[accent,glow,dark]=spec.palette;return `<!doctype html><html><head><meta charset="UTF-8"><style>
@font-face{font-family:"PingFang SC";src:local("PingFang SC")}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:${dark};font-family:Arial,"PingFang SC",sans-serif}.stage{position:relative;width:960px;height:540px;color:#fff;overflow:hidden;background:radial-gradient(circle at 72% 25%,${glow}88 0,transparent 30%),linear-gradient(135deg,${dark},#1b1d3b)}.grid{position:absolute;inset:0;background-image:linear-gradient(#ffffff0d 1px,transparent 1px),linear-gradient(90deg,#ffffff0d 1px,transparent 1px);background-size:40px 40px}.orb{position:absolute;border-radius:50%;filter:blur(2px)}#orb-a{width:260px;height:260px;left:-80px;bottom:-110px;background:linear-gradient(140deg,${accent}bb,transparent)}#orb-b{width:180px;height:180px;right:70px;top:45px;border:1px solid ${glow};box-shadow:0 0 80px ${glow}55}.copy{position:absolute;inset:0;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center}.eyebrow{font-size:13px;letter-spacing:6px;color:${accent};margin-bottom:20px}.title{font:700 68px Georgia,"Songti SC",serif;margin:0;letter-spacing:-2px;text-shadow:0 10px 40px #000a}.subtitle{font-size:14px;letter-spacing:5px;color:#d5d7e8;margin-top:22px}.line{width:0;height:2px;background:${accent};margin-top:25px}.frame{position:absolute;inset:22px;border:1px solid #ffffff1e}.code{position:absolute;left:30px;bottom:22px;color:#ffffff55;font:10px monospace}
</style></head><body><div id="stage" class="stage" data-composition-id="hypercut-main" data-no-timeline data-start="0" data-duration="${spec.duration}" data-width="960" data-height="540" data-fps="24"><div class="grid"></div><div class="frame"></div><div id="orb-a" class="orb"></div><div id="orb-b" class="orb"></div><div class="copy"><div id="eyebrow_01" class="eyebrow clip" data-start="0" data-duration="6" data-track-index="1">${escapeHtml(spec.subtitle)}</div><h1 id="title_01" class="title clip" data-start="0" data-duration="6" data-track-index="2">${escapeHtml(spec.title)}</h1><div id="subtitle_01" class="subtitle clip" data-start="0" data-duration="6" data-track-index="3">π AGENT × HYPERFRAMES</div><div id="line_01" class="line"></div></div><div class="code">GENERATED / 24 FPS / 006 SEC</div></div><script>
window.addEventListener('hf-seek',event=>{const t=event.detail.time||0,p=Math.min(1,t/1.2),out=Math.max(0,Math.min(1,(6-t)/.8)),ease=1-Math.pow(1-p,3),title=document.querySelector('.title');title.style.opacity=p*out;title.style.transform='translateY('+((1-ease)*50)+'px) scale('+(0.92+ease*.08)+')';document.querySelector('.eyebrow').style.opacity=Math.min(1,t/.7)*out;document.querySelector('.subtitle').style.opacity=Math.max(0,Math.min(1,(t-.5)/.8))*out;document.querySelector('.line').style.width=(Math.min(1,Math.max(0,(t-.8)/1.2))*320)+'px';document.querySelector('#orb-a').style.transform='translate('+(t*12)+'px,'+(-t*5)+'px) rotate('+(t*18)+'deg)';document.querySelector('#orb-b').style.transform='translateY('+(Math.sin(t*1.5)*16)+'px) rotate('+(t*-12)+'deg)'});
</script></body></html>`}

async function applyGeneratedState(spec,prompt){const current=await state();current.meta={...current.meta,duration:spec.duration,width:960,height:540,fps:24};const title=current.elements.find(e=>e.id==="title_01");title.text=spec.title;title.duration=spec.duration;title.fontSize=68;current.lastPrompt=prompt;await writeFile(stateFile,JSON.stringify(current,null,2)+"\n");return current}
function buildRenderEnv(){const ffmpegDir=path.join(root,"node_modules/ffmpeg-static"),ffprobeDir=path.dirname(ffprobePath);return{...process.env,PATH:[ffmpegDir,ffprobeDir,process.env.PATH||""].join(path.delimiter)}}
function renderTo(jobId,outputFile){return new Promise(resolve=>{const job=jobs.get(jobId);if(job){job.status="rendering";job.message="HyperFrames 正在逐帧渲染…"}let log="",settled=false;const done=(code,signal)=>{if(settled)return;settled=true;resolve({code,log,signal})};const child=spawn(process.execPath,[hyperframesScript,"render",compositionDir,"-o",outputFile,"-q","draft","-w","1","--quiet"],{cwd:root,env:buildRenderEnv()});child.stdout.on("data",d=>log+=d);child.stderr.on("data",d=>log+=d);child.on("error",error=>{log+=String(error.message||error);done(1,undefined)});child.on("close",(code,signal)=>done(code??(signal?1:0),signal))})}
async function concatenateSegments(segFiles,outputFile){if(!ffmpegBinary)throw new Error("ffmpeg-static 未安装");const listFile=outputFile+".txt";await writeFile(listFile,segFiles.map(f=>`file '${f.replace(/\\/g,"/")}'`).join("\n"),"utf8");return new Promise(resolve=>{let log="",settled=false;const done=code=>{if(settled)return;settled=true;resolve({code,log})};const child=spawn(ffmpegBinary,["-y","-f","concat","-safe","0","-i",listFile,"-c","copy",outputFile]);child.stdout.on("data",d=>log+=d);child.stderr.on("data",d=>log+=d);child.on("error",error=>{log+=String(error.message||error);done(1)});child.on("close",code=>done(code??1))})}
async function runSingleRender(jobId,outputFile){const{code,log,signal}=await renderTo(jobId,outputFile);const job=jobs.get(jobId);if(code===0){job.status="complete";job.message="视频已生成，可以播放";job.videoUrl=`/api/video/${path.basename(outputFile)}`}else if(job.status!=="failed"){job.status="failed";job.message=signal?`渲染进程被终止（${signal}）`:"渲染失败";job.error=log.slice(-1800)}}
async function runSegmentedGeneration(jobId,{prompt,style,spec,totalDuration,segCount,usingModel}){const segFiles=[];let prevHtml=null;for(let i=0;i<segCount;i++){const start=i*SEGMENT_SECONDS,dur=Math.min(SEGMENT_SECONDS,totalDuration-start),segStartFrame=Math.round(start*24),segDurFrames=Math.round(dur*24),job=jobs.get(jobId);job.status="coding";job.message=segCount>1?`正在生成第 ${i+1}/${segCount} 段（${start}s–${start+dur}s）…`:"正在生成视频…";const generated=usingModel?await generateCompositionWithPiAgent({prompt,seed:spec,style,segment:{index:i,count:segCount,start,duration:dur,total:totalDuration,previousHtml:prevHtml}}):{html:generateComposition({...spec,duration:dur}),summary:"本地模板生成",model:"local-deterministic"};prevHtml=generated.html;const html=await applyAudioTrack(forceSegmentDuration(generated.html,dur),segStartFrame,segDurFrames);await writeFile(compositionFile,html);job.code=html;job.summary=generated.summary;job.model=generated.model;const segFile=segCount===1?path.join(outputDir,`hypercut-${jobId}.mp4`):path.join(outputDir,`hypercut-${jobId}-seg${i}.mp4`);const{code,log,signal}=await renderTo(jobId,segFile);if(code!==0){job.status="failed";job.message=signal?`渲染进程被终止（${signal}）`:"渲染失败";job.error=log.slice(-1800);return}segFiles.push(segFile);job.segmentInfo={total:segCount,done:i+1};if(segCount>1&&i<segCount-1){job.status="segment";job.message=`第 ${i+1}/${segCount} 段完成，已可预览，继续生成剩余部分…`;job.videoUrl=`/api/video/${path.basename(segFile)}`}}if(segCount>1){const finalFile=path.join(outputDir,`hypercut-${jobId}.mp4`),job=jobs.get(jobId);job.status="rendering";job.message="正在拼接所有片段…";const{code,log}=await concatenateSegments(segFiles,finalFile);if(code!==0){job.status="failed";job.message="拼接失败";job.error=log.slice(-1800);return}job.status="complete";job.message="长视频已生成，可以播放";job.videoUrl=`/api/video/${path.basename(finalFile)}`}else{const job=jobs.get(jobId);job.status="complete";job.message="视频已生成，可以播放";job.videoUrl=`/api/video/${path.basename(segFiles[0])}`}}
async function generate(prompt,durationOverride,styleId){const jobId=crypto.randomUUID(),style=(styleId&&styleId!=="auto")?getStyle(styleId):detectStyle(prompt),spec=understandPrompt(prompt,style),requestedDuration=Number(durationOverride);if(Number.isFinite(requestedDuration))spec.duration=Math.max(2,Math.min(60,requestedDuration));const totalDuration=spec.duration,segCount=Math.max(1,Math.ceil(totalDuration/SEGMENT_SECONDS)),usingModel=Boolean(process.env.MODEL_API_KEY)&&process.env.HYPERCUT_AGENT_MODE!=="local",version=++projectVersion,current=await applyGeneratedState(spec,prompt),modelName=usingModel?(process.env.PI_MODEL||"pi-agent"):"local-deterministic";jobs.set(jobId,{id:jobId,status:"coding",kind:"generate",version,message:`${modelName} 已开始生成`,prompt,spec,style:style.name,code:"",summary:"",model:modelName,segmentInfo:{total:segCount,done:0},totalDuration,segCount,createdAt:Date.now()});runSegmentedGeneration(jobId,{prompt,style,spec,totalDuration,segCount,usingModel}).catch(err=>{const job=jobs.get(jobId);if(job){job.status="failed";job.message=err instanceof Error?err.message:"生成失败";job.error=String(err)}});return{jobId,state:current,spec,style:style.id,version,segments:segCount,totalDuration,mode:usingModel?"pi-agent":"local-agent",model:modelName,tools:["get_editing_state","write_composition","hyperframes_render"]}}
async function modify(prompt,targetFrame){const current=await state(),fps=Number(current.meta?.fps)||24,duration=Number(current.meta?.duration)||6,maxFrame=Math.max(0,Math.ceil(duration*fps)-1),frame=Math.max(0,Math.min(maxFrame,Math.round(Number(targetFrame)||0))),html=await readFile(compositionFile,"utf8");if(!process.env.MODEL_API_KEY)throw new Error("实时修改需要配置 MODEL_API_KEY");const generated=await modifyCompositionWithPiAgent({prompt,html,targetFrame:frame,fps}),jobId=crypto.randomUUID(),outputFile=path.join(outputDir,`hypercut-edit-${jobId}.mp4`),version=++projectVersion,audioHtml=await applyAudioTrack(generated.html);await writeFile(compositionFile,audioHtml);current.lastPrompt=prompt;current.lastEdit={frame,time:frame/fps,prompt,version};await writeFile(stateFile,JSON.stringify(current,null,2)+"\n");jobs.set(jobId,{id:jobId,status:"coding",kind:"edit",version,targetFrame:frame,targetTime:frame/fps,message:`${generated.model} 已在第 ${frame} 帧修改代码`,prompt,code:audioHtml,summary:generated.summary,model:generated.model,createdAt:Date.now()});setTimeout(()=>runSingleRender(jobId,outputFile),80);return{jobId,version,targetFrame:frame,targetTime:frame/fps,model:generated.model,mode:"incremental-edit"}}
async function renderAudioChange(kind="audio"){const html=await applyAudioTrack(await readFile(compositionFile,"utf8")),jobId=crypto.randomUUID(),version=++projectVersion,outputFile=path.join(outputDir,`hypercut-audio-${jobId}.mp4`);await writeFile(compositionFile,html);jobs.set(jobId,{id:jobId,status:"coding",kind,version,message:"音轨已更新，准备重新渲染",code:html,summary:"音轨设置已更新",model:"audio-editor",createdAt:Date.now()});setTimeout(()=>runSingleRender(jobId,outputFile),80);return{jobId,version}}
async function serveVideo(req,res,file){try{const info=await stat(file),range=req.headers.range;res.setHeader("accept-ranges","bytes");res.setHeader("content-type","video/mp4");res.setHeader("cache-control","no-store");if(!range){res.writeHead(200,{"content-length":info.size});return createReadStream(file).pipe(res)}const[startText,endText]=range.replace("bytes=","").split("-"),start=Number(startText),end=endText?Number(endText):Math.min(start+1024*1024,info.size-1);res.writeHead(206,{"content-range":`bytes ${start}-${end}/${info.size}`,"content-length":end-start+1});return createReadStream(file,{start,end}).pipe(res)}catch{res.writeHead(404);res.end("Video not found")}}
async function serveAudioAsset(req,res,asset){try{const file=audioStore.filePath(asset),info=await stat(file),range=req.headers.range;res.setHeader("accept-ranges","bytes");res.setHeader("content-type",audioStore.contentType(asset));res.setHeader("cache-control","no-store");if(!range){res.writeHead(200,{"content-length":info.size});return createReadStream(file).pipe(res)}const[startText,endText]=range.replace("bytes=","").split("-"),start=Number(startText),end=endText?Number(endText):Math.min(start+1024*1024,info.size-1);res.writeHead(206,{"content-range":`bytes ${start}-${end}/${info.size}`,"content-length":end-start+1});return createReadStream(file,{start,end}).pipe(res)}catch{res.writeHead(404);res.end("Audio not found")}}

const server=http.createServer(async(req,res)=>{
 try{
  res.setHeader("access-control-allow-origin","*");res.setHeader("access-control-allow-headers","content-type, range");
  if(req.method==="OPTIONS"){res.writeHead(204);return res.end()}
  const url=new URL(req.url,`http://${req.headers.host||"localhost"}`);
  if(url.pathname==="/api/health")return json(res,{ok:true,agent:"pi-agent-core",model:process.env.PI_MODEL||null,apiConfigured:Boolean(process.env.MODEL_API_KEY),video:"hyperframes",incrementalEdit:true,audio:true});
  if(url.pathname==="/api/state")return json(res,await state());
  if(url.pathname==="/api/audio"&&req.method==="GET")return json(res,await audioStore.resolveTrack());
  if(url.pathname==="/api/assets"&&req.method==="POST"){const request=new Request("http://localhost/api/assets",{method:"POST",headers:req.headers,body:Readable.toWeb(req),duplex:"half"}),form=await request.formData(),asset=await audioStore.importAsset(form.get("file"));return json(res,{ok:true,asset},201)}
  if(url.pathname.match(/^\/api\/assets\/[^/]+\/file$/)&&req.method==="GET"){const id=url.pathname.split("/")[3],data=await audioStore.load(),asset=data.assets.find(item=>item.id===id);return asset?serveAudioAsset(req,res,asset):json(res,{error:"音频素材不存在"},404)}
  if(url.pathname.startsWith("/api/assets/")&&req.method==="DELETE"){const id=url.pathname.split("/")[3];await audioStore.removeAsset(id);return json(res,{ok:true,...await renderAudioChange("audio-remove")},202)}
  if(url.pathname==="/api/audio-track"&&req.method==="PUT"){let body="";for await(const chunk of req)body+=chunk;const result=await audioStore.updateTrack(JSON.parse(body||"{}")),render=await renderAudioChange("audio-update");return json(res,{ok:true,...result,...render},202)}
  if(url.pathname==="/api/audio-track"&&req.method==="DELETE"){await audioStore.clearTrack();return json(res,{ok:true,...await renderAudioChange("audio-remove")},202)}
  if(url.pathname==="/api/styles")return json(res,{styles:STYLES.map(({id,name,icon,description,palette})=>({id,name,icon,description,palette})),segmentSeconds:SEGMENT_SECONDS});
  if(url.pathname==="/api/agent/generate"&&req.method==="POST"){let body="";for await(const chunk of req)body+=chunk;const{prompt="",duration,style="auto"}=JSON.parse(body||"{}");if(!prompt.trim())return json(res,{error:"prompt is required"},400);return json(res,{ok:true,...(await generate(prompt,duration,style))},202)}
  if(url.pathname==="/api/agent/modify"&&req.method==="POST"){let body="";for await(const chunk of req)body+=chunk;const{prompt="",targetFrame=0}=JSON.parse(body||"{}");if(!prompt.trim())return json(res,{error:"prompt is required"},400);return json(res,{ok:true,...(await modify(prompt,targetFrame))},202)}
  if(url.pathname.match(/^\/api\/jobs\/[^/]+\/code$/)){const id=url.pathname.split("/")[3],job=jobs.get(id);return job?json(res,{code:job.code,summary:job.summary,model:job.model,kind:job.kind,version:job.version,targetFrame:job.targetFrame,targetTime:job.targetTime}):json(res,{error:"job not found"},404)}
  if(url.pathname.startsWith("/api/jobs/")){const job=jobs.get(url.pathname.split("/").pop());if(!job)return json(res,{error:"job not found"},404);const{code,...status}=job;return json(res,status)}
  if(url.pathname.startsWith("/api/video/"))return serveVideo(req,res,path.join(outputDir,path.basename(url.pathname)));
  res.writeHead(404);res.end("Not found");
 }catch(error){console.error(error);return json(res,{error:error instanceof Error?error.message:"Internal error"},500)}
});
server.listen(port,"127.0.0.1",()=>console.log(`HyperCut agent API: http://localhost:${port}`));
